# -*- coding: utf-8 -*-
"""frames.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vGb4cqdkCwqDMDvmlFNhpiZak76Fs0oc
"""

# --- Bloco 1: Instalação e Imports (Com Force Remount) ---
print("Instalando bibliotecas...")
!pip install transformers torch pandas tqdm sentencepiece

import pandas as pd
import torch
from transformers import pipeline
from tqdm.auto import tqdm
import os
import gc
from google.colab import drive

# Tenta montar com força bruta para corrigir o erro
print("Tentando montar o Drive...")
try:
    drive.mount('/content/drive', force_remount=True)
    print("✅ Drive montado com sucesso.")
except Exception as e:
    print(f"❌ Falha ao montar: {e}")
    print("Tente reiniciar o ambiente de execução (Runtime -> Disconnect and delete runtime).")

print("Ambiente pronto.")

# --- Bloco 2: Carregar Dados e Modelo ZSC (Otimizado) ---

# 1. Caminhos
# Lemos o arquivo que SAÍU do passo anterior (que já tem emoções)
CAMINHO_ENTRADA = "/content/drive/MyDrive/WAPOR_DISSERTACAO/dados/base_dados_COM_EMOCOES.csv"
MODELO_ZSC = "joeddav/xlm-roberta-large-xnli"

# 2. Carregar Dados
try:
    # Lembre-se: usamos sep=';' no passo anterior
    df_analise = pd.read_csv(CAMINHO_ENTRADA, sep=';')
    print(f"Dataset carregado: {df_analise.shape[0]} linhas.")

    # Filtra apenas para garantir que não pegamos linhas vazias
    df_validos = df_analise[df_analise['transcricao'].notna() & (df_analise['transcricao'].str.strip() != "")].copy()
    print(f"Vídeos válidos para processar: {len(df_validos)}")

except FileNotFoundError:
    print(f"ERRO: Arquivo '{CAMINHO_ENTRADA}' não encontrado.")

# 3. Carregar Modelo na GPU com FP16 (Otimização L4)
device = 0 if torch.cuda.is_available() else -1

if device == 0:
    print(f"🚀 GPU Detectada! Ativando otimização float16 para L4...")
    dtype = torch.float16
else:
    print("AVISO: GPU não detectada. Isso vai demorar.")
    dtype = torch.float32

try:
    print(f"Carregando {MODELO_ZSC}...")
    zsc_classifier = pipeline(
        "zero-shot-classification",
        model=MODELO_ZSC,
        tokenizer=MODELO_ZSC,
        device=device,
        torch_dtype=dtype # <--- AQUI ESTÁ A OTIMIZAÇÃO
    )
    print("✅ Modelo ZSC carregado com sucesso (Modo Rápido).")
except Exception as e:
    print(f"Erro ao carregar modelo: {e}")

# --- Bloco 3: Função de Processamento de FRAMES (Média Ponderada) ---
import numpy as np

# Definir os Rótulos (Master Frames) aqui para garantir que existam
LABELS_FRAMES = [
    "ameaça à liberdade",       # Diagnóstico
    "vitimismo",                # Afetivo
    "defesa da liberdade",      # Valor
    "resistência e mobilização" # Motivacional
]

CHUNK_SIZE = 500

def get_frame_scores(text):
    """
    Processa transcrição, quebra em chunks e calcula
    MÉDIA PONDERADA dos FRAMES.
    """
    # Usa o tokenizer do ZSC
    tokens = zsc_classifier.tokenizer(text, return_tensors="pt", truncation=False)['input_ids'][0]
    chunk_data = []

    for i in range(0, len(tokens), CHUNK_SIZE):
        chunk_tokens = tokens[i:i+CHUNK_SIZE]
        chunk_text = zsc_classifier.tokenizer.decode(chunk_tokens, skip_special_tokens=True)

        # Peso = tamanho do chunk
        weight = len(chunk_tokens)

        if chunk_text.strip():
            try:
                # Roda o ZSC com os labels de Frame
                result = zsc_classifier(chunk_text, LABELS_FRAMES, multi_label=True)

                scores_dict = {label: score for label, score in zip(result['labels'], result['scores'])}
                scores_dict['_weight'] = weight
                chunk_data.append(scores_dict)
            except Exception as e:
                continue

    if not chunk_data:
        return None

    # --- CÁLCULO DA MÉDIA PONDERADA ---
    df_chunks = pd.DataFrame(chunk_data)
    total_weight = df_chunks['_weight'].sum()
    final_scores = {}

    for col in df_chunks.columns:
        if col != '_weight':
            weighted_mean = (df_chunks[col] * df_chunks['_weight']).sum() / total_weight
            # Renomeia para frame_...
            # Substitui espaços por _ para o CSV ficar limpo
            clean_col = col.replace(' ', '_')
            final_scores[f"frame_{clean_col}"] = weighted_mean

    return final_scores

# --- Bloco 4: Executar e Salvar ---

print(f"Iniciando análise de FRAMES em {len(df_validos)} vídeos...")
# Na L4, isso deve levar entre 45min a 1h30min (bem mais rápido que na T4)
tqdm.pandas(desc="Analisando Frames")

frame_results = df_validos['transcricao'].progress_apply(get_frame_scores)

# Organiza os resultados
df_scores_frames = pd.json_normalize(frame_results)
df_scores_frames.index = df_validos.index

# Junta com o DF original (que já tem as emoções)
df_final_completo = pd.concat([df_validos, df_scores_frames], axis=1)

# CAMINHO FINAL
CAMINHO_FINAL = "/content/drive/MyDrive/WAPOR_DISSERTACAO/dados/base_dados_FINAL_IA.csv"

# Salva com ';'
df_final_completo.to_csv(CAMINHO_FINAL, index=False, sep=';')

print(f"--- SUCESSO TOTAL ---")
print(f"Arquivo FINAL salvo em: {CAMINHO_FINAL}")
print("Este arquivo contém:")
print("1. Transcrições Limpas")
print("2. Scores de Emoção (BERTimbau)")
print("3. Scores de Frame (ZSC Large)")
print(df_final_completo.head(2))

# --- Bloco de Correção Final (Pós-Processamento) ---
import pandas as pd

# 1. Carregar o arquivo FINAL que você acabou de gerar
CAMINHO_FINAL = "/content/drive/MyDrive/WAPOR_DISSERTACAO/dados/base_dados_FINAL_IA.csv"

print(f"Lendo arquivo: {CAMINHO_FINAL}")
df_final = pd.read_csv(CAMINHO_FINAL, sep=';')

# 2. Mapeamento das Emoções (Caso estejam como LABEL_X)
mapa_emocoes = {
    'LABEL_0': 'raiva',
    'LABEL_1': 'medo',
    'LABEL_2': 'alegria',
    'LABEL_3': 'tristeza',
    'LABEL_4': 'surpresa',
    'LABEL_5': 'nojo',
    'LABEL_6': 'neutro',
    # Caso o modelo tenha salvo como 'emo_LABEL_0' (com prefixo)
    'emo_LABEL_0': 'raiva',
    'emo_LABEL_1': 'medo',
    'emo_LABEL_2': 'alegria',
    'emo_LABEL_3': 'tristeza',
    'emo_LABEL_4': 'surpresa',
    'emo_LABEL_5': 'nojo',
    'emo_LABEL_6': 'neutro'
}

# 3. Renomear
df_final = df_final.rename(columns=mapa_emocoes)

# 4. Verificação Visual
print("\n--- Verificando Colunas ---")
colunas_emo = [c for c in df_final.columns if 'emo_' in c]
colunas_frame = [c for c in df_final.columns if 'frame_' in c]

print(f"Colunas de Emoção ({len(colunas_emo)}): {colunas_emo}")
print(f"Colunas de Frame ({len(colunas_frame)}): {colunas_frame}")

# 5. Salvar de volta (Sobrescrever com a versão corrigida)
df_final.to_csv(CAMINHO_FINAL, index=False, sep=';')
print(f"\nArquivo corrigido salvo com sucesso em: {CAMINHO_FINAL}")