# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12VA_DEvgvOumf0GUMm2zx-2CjqH6l23l
"""

## ==============================================================================
# SCRIPT CORRIGIDO: GEMINI 2.5 PRO (PROBLEMA id_video RESOLVIDO)
# ==============================================================================

# 1. Reset e Instalação
from google.colab import drive
drive.mount('/content/drive')

print("Instalando bibliotecas...")
!pip install -q -U google-generativeai pandas tqdm tenacity

import google.generativeai as genai
import pandas as pd
import json
import time
import os
import re
import signal
from tqdm.auto import tqdm
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type
from json import JSONDecoder
from google.api_core.exceptions import InvalidArgument, ResourceExhausted

# --- CONFIGURAÇÃO ---

# Caminhos
BASE_PATH = "/content/drive/MyDrive/WAPOR_DISSERTACAO/dados"
CAMINHO_CHAVE = os.path.join(BASE_PATH, "API_GEMINI.txt")

# Carregar API Key do arquivo
print(f"Lendo chave de API em: {CAMINHO_CHAVE}")
try:
    with open(CAMINHO_CHAVE, "r") as f:
        GOOGLE_API_KEY = f.read().strip()

    if not GOOGLE_API_KEY:
        raise ValueError("O arquivo de chave está vazio!")

    genai.configure(api_key=GOOGLE_API_KEY)
    print("✅ API Configurada com sucesso!")

except Exception as e:
    print(f"❌ Erro fatal ao ler a chave: {e}")
    print("Verifique se o arquivo 'API_GEMINI.txt' existe na pasta 'dados'.")
    raise e

# Caminhos de Dados
ARQUIVO_ENTRADA = os.path.join(BASE_PATH, "transcricoes.csv")
if not os.path.exists(ARQUIVO_ENTRADA):
    ARQUIVO_ENTRADA = os.path.join(BASE_PATH, "base_dados_MESTRE_ANALISE.csv")

ARQUIVO_SAIDA = os.path.join(BASE_PATH, "base_dados_FINAL_UNIFICADO.csv")
ARQUIVO_CHECKPOINT = os.path.join(BASE_PATH, "checkpoint_unificado.csv")

print(f"Lendo dados de: {ARQUIVO_ENTRADA}")

# 2. Configuração do Modelo (Safety OFF)
safety_settings = [
    {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE"},
    {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE"},
    {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_NONE"},
    {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_NONE"},
]

generation_config = {
  "temperature": 0.0,
  "response_mime_type": "application/json",
}

# Prompt Teórico Completo
system_prompt = """Você é um assistente de pesquisa sociológica especializado em análise de discurso e extrema-direita.
Analise a transcrição e atribua pontuações de 0.00000 a 1.00000 para cada dimensão (use 5 casas decimais).

PARTE 1: FRAMES (Liberdade Reacionária - Szwako, 2023)
1. frame_ameaca_a_liberdade: Representação do Estado como inimigo da liberdade, associando regulação à censura, autoritarismo e ditadura, com menções ao STF como símbolo dessa ameaça (instrumentalização da liberdade como escudo contra regulação).
2. frame_vitimismo: Construção de identidade coletiva perseguida, narrativas de silenciamento ('nos calaram'), sistema contra o grupo, reforçando sensação de vitimização e injustiça.
3. frame_desconfianca_epistemica: Guerra à mídia tradicional e instituições de verificação (Globo, fact-checkers), acusações de manipulação informacional, erosão da confiança em fontes hegemônicas.
4. frame_religioso_moral: Pânico moral associando regulação à censura religiosa (Bíblia), perseguição a cristãos, defesa da família tradicional e liberdade religiosa como bastiões contra avanços progressistas.
5. frame_resistencia_e_mobilizacao: Imperativo de ação coletiva, chamados para resistência, mobilização nas ruas, não aceitação da regulação, constituindo trajetória emocional de conversão em engajamento.

PARTE 2: EMOÇÕES (Performance - Jasper, 2011; Flam, 2014)
1. emo_raiva: Indignação moral, fúria justa, reação a transgressões percebidas, combustível para ação coletiva.
2. emo_alegria: Celebração de vitórias, entusiasmo, orgulho identitário, afeto mobilizador de coesão.
3. emo_medo: Alerta de perigo iminente, temor de perdas culturais/morais, atmosfera de ameaça existencial.
4. emo_tristeza: Lamento por perdas simbólicas, derrota, sofrimento coletivo, melancolia política.
5. emo_neutro: Tom técnico-informacional, neutralidade emocional, discurso factual sem carga afetiva.

SAÍDA OBRIGATÓRIA (JSON):
{
  "frame_ameaca_a_liberdade": 0.00000,
  "frame_vitimismo": 0.00000,
  "frame_desconfianca_epistemica": 0.00000,
  "frame_religioso_moral": 0.00000,
  "frame_resistencia_e_mobilizacao": 0.00000,
  "emo_raiva": 0.00000,
  "emo_alegria": 0.00000,
  "emo_medo": 0.00000,
  "emo_tristeza": 0.00000,
  "emo_neutro": 0.00000
}
"""

model = genai.GenerativeModel(
  model_name="models/gemini-2.5-pro",
  generation_config=generation_config,
  system_instruction=system_prompt,
  safety_settings=safety_settings
)

# 3. Carregar Dados
try:
    df = pd.read_csv(ARQUIVO_ENTRADA, sep=';')
    # CORREÇÃO: Garantir que id_video está presente
    if 'id_video' not in df.columns:
        print("❌ ERRO: Coluna 'id_video' não encontrada no arquivo de entrada!")
        print(f"Colunas disponíveis: {list(df.columns)}")
        raise KeyError("Coluna 'id_video' não encontrada")

    df_validos = df[df['transcricao'].notna() & (df['transcricao'].str.strip() != "")].copy()
    print(f"Vídeos para classificar: {len(df_validos)}")
    print(f"Colunas disponíveis: {list(df_validos.columns)}")
except Exception as e:
    print(f"ERRO ao ler arquivo de entrada: {e}")
    raise e

# --- FUNÇÕES BLINDADAS ---

CHECKPOINT_INTERVAL = 5
MAX_CHARS = 35000
EXPECTED_KEYS = [
    "frame_ameaca_a_liberdade", "frame_vitimismo", "frame_desconfianca_epistemica",
    "frame_religioso_moral", "frame_resistencia_e_mobilizacao",
    "emo_raiva", "emo_alegria", "emo_medo", "emo_tristeza", "emo_neutro"
]

def extract_json_robust(text):
    try: return json.loads(text)
    except: pass
    start = text.find('{')
    if start == -1: return None
    try:
        decoder = JSONDecoder()
        obj, end = decoder.raw_decode(text[start:])
        return obj
    except:
        m = re.search(r"\{.*\}", text, re.DOTALL)
        if m:
            try: return json.loads(m.group(0))
            except: pass
        return None

@retry(
    wait=wait_exponential(min=5, max=60),
    stop=stop_after_attempt(10),
    retry=retry_if_exception_type((ResourceExhausted, Exception))
)
def gerar_resposta_com_retry(prompt):
    try:
        response = model.generate_content(prompt)
        return response.text
    except InvalidArgument:
        raise ValueError("ERRO_400_PULAR_VIDEO")
    except Exception as e:
        if "400" in str(e): raise ValueError("ERRO_400_PULAR_VIDEO")
        raise e

def analisar_unificado(texto):
    prompt = f"Analise a transcrição completa:\n---\n{texto[:MAX_CHARS]}\n---\nPontue Frames e Emoções."

    try:
        raw_text = gerar_resposta_com_retry(prompt)
        resultado = extract_json_robust(raw_text)

        if resultado:
            return {k: resultado.get(k, 0.0) for k in EXPECTED_KEYS}
        else:
            return {k: 0.0 for k in EXPECTED_KEYS}

    except ValueError as ve:
        if "ERRO_400" in str(ve):
            print("⚠️ Vídeo tóxico/inválido (400). Pulando...")
            return {k: 0.0 for k in EXPECTED_KEYS}
        return {k: 0.0 for k in EXPECTED_KEYS}

    except Exception as e:
        print(f"Erro: {e}")
        return {k: 0.0 for k in EXPECTED_KEYS}
    finally:
        time.sleep(4)

# --- LOOP PRINCIPAL CORRIGIDO ---
print("Iniciando análise (Modo Seguro - 10s delay)...")

# CORREÇÃO: Usar id_video em vez do índice
indices = df_validos.index.tolist()
resultados = []
start_pos = 0

if os.path.exists(ARQUIVO_CHECKPOINT):
    try:
        df_check = pd.read_csv(ARQUIVO_CHECKPOINT, sep=';')
        if "id_video" in df_check.columns:  # CORREÇÃO: Verificar por id_video
            resultados = df_check.to_dict('records')
            start_pos = len(resultados)
            print(f"✅ Checkpoint carregado! Retomando do vídeo {start_pos}...")
    except Exception as e:
        print(f"⚠️ Erro ao carregar checkpoint: {e}")

def salvar_checkpoint(rows):
    dfp = pd.DataFrame(rows)
    dfp.to_csv(ARQUIVO_CHECKPOINT, sep=';', index=False)

def handle_sigint(signum, frame):
    print("\nSalvando antes de sair...")
    salvar_checkpoint(resultados)
    raise KeyboardInterrupt()

signal.signal(signal.SIGINT, handle_sigint)

for pos in tqdm(range(start_pos, len(indices)), desc="Processando"):
    idx = indices[pos]
    texto = df_validos.at[idx, 'transcricao']
    # CORREÇÃO PRINCIPAL: Salvar o id_video real
    id_video = df_validos.at[idx, 'id_video']

    res = analisar_unificado(texto)
    # CORREÇÃO: Incluir id_video em vez do índice
    res_with_id = {"id_video": id_video}
    res_with_id.update(res)
    resultados.append(res_with_id)

    if (pos + 1) % CHECKPOINT_INTERVAL == 0:
        salvar_checkpoint(resultados)

# --- FINALIZAÇÃO CORRIGIDA ---
print("Salvando arquivo final...")
df_res = pd.DataFrame(resultados)

# CORREÇÃO: Juntar pelo id_video em vez do índice
if "id_video" in df_res.columns:
    # Garantir que df_validos tem id_video
    if "id_video" in df_validos.columns:
        # Fazer merge pelo id_video
        df_final = df_validos.merge(df_res, on='id_video', how='left')

        # Preencher NaN com 0.0 para as colunas de análise
        for col in EXPECTED_KEYS:
            if col in df_final.columns:
                df_final[col] = df_final[col].fillna(0.0)

        df_final.to_csv(ARQUIVO_SAIDA, sep=';', index=False)
        print(f"\n✅ Sucesso! Arquivo salvo em: {ARQUIVO_SAIDA}")
        print(f"✅ Colunas no arquivo final: {list(df_final.columns)}")
    else:
        print("❌ ERRO: Coluna 'id_video' não encontrada em df_validos")
        df_res.to_csv(ARQUIVO_SAIDA, sep=';', index=False)
else:
    print("⚠️ Salvando arquivo parcial (sem id_video)...")
    df_res.to_csv(ARQUIVO_SAIDA, sep=';', index=False)

print("✅ Processo concluído!")

# 1. Reset e Instalação
from google.colab import drive
drive.mount('/content/drive')

# DIAGNÓSTICO DOS DADOS
import pandas as pd
import matplotlib.pyplot as plt
import os

# Carrega o dataframe (ajuste o caminho se necessário)
BASE_PATH = "/content/drive/MyDrive/WAPOR_DISSERTACAO/dados"
ARQUIVO_ENTRADA = os.path.join(BASE_PATH, "base_dados_MESTRE_ANALISE.csv") # ou transcricoes.csv
df = pd.read_csv(ARQUIVO_ENTRADA, sep=';')
df_validos = df[df['transcricao'].notna()].copy()

# Calcula tamanho em caracteres
df_validos['tamanho_char'] = df_validos['transcricao'].apply(len)

# Estatísticas
print(f"Total de vídeos: {len(df_validos)}")
print(f"Tamanho Médio: {df_validos['tamanho_char'].mean():.0f} caracteres")
print(f"Tamanho Máximo: {df_validos['tamanho_char'].max():.0f} caracteres")
print(f"Vídeos > 30.000 chars: {len(df_validos[df_validos['tamanho_char'] > 30000])}")

# Histograma para ver a distribuição
df_validos['tamanho_char'].hist(bins=50)
plt.title("Distribuição do Tamanho das Transcrições")
plt.xlabel("Caracteres")
plt.show()